$(function(){
	 $(document).ready(function(){
			  var showproduct = {
				  "boxid":"showbox",
				  "sumid":"showsum",
				  "boxw":340,//宽度,该版本中请把宽高填写成一样
				  "boxh":350,//高度,该版本中请把宽高填写成一样
				  "sumw":58,//列表每个宽度,该版本中请把宽高填写成一样
				  "sumh":58,//列表每个高度,该版本中请把宽高填写成一样
				  "sumi":7,//列表间隔
				  "sums":2,//列表显示个数
				  "sumsel":"sel",
				  "sumborder":1,//列表边框，没有边框填写0，边框在css中修改
				  "lastid":"showlast",
				  "nextid":"shownext"
				  };//参数定义	  
			 $.ljsGlasses.pcGlasses(showproduct);//方法调用，务必在加载完后执行
		  });
})